export const tableOption = {
    "border": true,
    "filterBtn":true,
    "index": true,
    "indexLabel": "序号",
    "stripe": true,
    "menuAlign": "center",
    "align": "center",
    "size":"mini",
    "selection":true,
    "searchMenuSpan": 6,
    "selectionWidth":40,
    "menuWidth":160,
    "menuPosition":"center",
    "height":550,
    "column": [
                    {
                "type": "input",
                "label": "货种",
                "prop": "cargoKindId"
            },                    {
                "type": "input",
                "label": "作业委托人代码",
                "prop": "consignCod"
            },                    {
                "type": "input",
                "label": "委托人代表",
                "prop": "consignMan"
            },                    {
                "type": "input",
                "label": "作业委托人",
                "prop": "consignNam"
            },                    {
                "type": "input",
                "label": "委托人电话",
                "prop": "consignPhone"
            },                    {
                "type": "input",
                "label": "经办日期",
                "prop": "contDte"
            },                    {
                "type": "input",
                "label": "合同号",
                "prop": "contNo"
            },                    {
                "type": "input",
                "label": "合同条款",
                "prop": "contTxt"
            },                    {
                "type": "input",
                "label": "作废",
                "prop": "deposeId"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "ifendId"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "lrRequNo"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "officeCod"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "officeMan"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "officeNam"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "officePhone"
            },                    {
                "type": "input",
                "label": "操作员",
                "prop": "operNam"
            },                    {
                "type": "input",
                "label": "批准否",
                "prop": "passId"
            },                    {
                "type": "input",
                "label": "放行数量",
                "prop": "passPiecesNum"
            },                    {
                "type": "input",
                "label": "放行备注",
                "prop": "passTxt"
            },                    {
                "type": "input",
                "label": "放行重量",
                "prop": "passWeightWgt"
            },                    {
                "type": "input",
                "label": "计划提货结束期限",
                "prop": "planLimitTim"
            },                    {
                "type": "input",
                "label": "记录时间",
                "prop": "recordTim"
            },                    {
                "type": "input",
                "label": "备注",
                "prop": "remarkTxt"
            },                    {
                "type": "input",
                "label": "申请单号",
                "prop": "requNo"
            },                    {
                "type": "input",
                "label": "堆存费收取标志",
                "prop": "stackFeeId"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "subunitCod"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "subunitNam"
            },                    {
                "type": "input",
                "label": "单位代码",
                "prop": "unitCod"
            },                    {
                "type": "input",
                "label": "单位名称",
                "prop": "unitNam"
            },                    {
                "type": "input",
                "label": "最终修改人",
                "prop": "updateNam"
            },                    {
                "type": "input",
                "label": "最终修改时间",
                "prop": "updateTim"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "upId"
            },                    {
                "type": "input",
                "label": "直取标志",
                "prop": "zqId"
            }            ]
}
