export const tableOption = {
    "border": true,
    "filterBtn":true,
    "index": true,
    "indexLabel": "序号",
    "stripe": true,
    "menuAlign": "center",
    "align": "center",
    "size":"mini",
    "selection":true,
    "searchMenuSpan": 6,
    "selectionWidth":40,
    "menuWidth":160,
    "menuPosition":"center",
    "height":550,
    "column": [
                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "addrNam"
            },                    {
                "type": "input",
                "label": "提单号",
                "prop": "billNo"
            },                    {
                "type": "input",
                "label": "货名",
                "prop": "cargoNam"
            },                    {
                "type": "input",
                "label": "货名代码",
                "prop": "cargoNamCod"
            },                    {
                "type": "input",
                "label": "货号",
                "prop": "cargoNo"
            },                    {
                "type": "input",
                "label": "体积",
                "prop": "cargoVol"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "carNo"
            },                    {
                "type": "input",
                "label": "计费单位",
                "prop": "cFeeUnit"
            },                    {
                "type": "input",
                "label": "包装",
                "prop": "cPkgKindNam"
            },                    {
                "type": "input",
                "label": "费率",
                "prop": "feeRat"
            },                    {
                "type": "input",
                "label": "计费单位代码",
                "prop": "feeUnitCod"
            },                    {
                "type": "input",
                "label": "规格",
                "prop": "format"
            },                    {
                "type": "input",
                "label": "入港日期",
                "prop": "inPortDte"
            },                    {
                "type": "input",
                "label": "进港方式",
                "prop": "inPortWay"
            },                    {
                "type": "input",
                "label": "入库方式",
                "prop": "inYardWay"
            },                    {
                "type": "input",
                "label": "加温时间",
                "prop": "loadingTim"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "lrRequNo"
            },                    {
                "type": "input",
                "label": "操作员",
                "prop": "operNam"
            },                    {
                "type": "input",
                "label": "出港方式",
                "prop": "outPortWay"
            },                    {
                "type": "input",
                "label": "出库方式",
                "prop": "outYardWay"
            },                    {
                "type": "input",
                "label": "件数",
                "prop": "piecesNum"
            },                    {
                "type": "input",
                "label": "包装代码",
                "prop": "pkgKindCod"
            },                    {
                "type": "input",
                "label": "记录时间",
                "prop": "recordTim"
            },                    {
                "type": "input",
                "label": "合同号",
                "prop": "requNo"
            },                    {
                "type": "input",
                "label": "险种",
                "prop": "safetyKndCod"
            },                    {
                "type": "input",
                "label": "序号",
                "prop": "seqNo"
            },                    {
                "type": "input",
                "label": "货主代码",
                "prop": "shipperCod"
            },                    {
                "type": "input",
                "label": "货主名称",
                "prop": "shipperDoc"
            },                    {
                "type": "input",
                "label": "船名",
                "prop": "shipNam"
            },                    {
                "type": "input",
                "label": "船号",
                "prop": "shipNo"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "steelNo"
            },                    {
                "type": "input",
                "label": "扫线次数",
                "prop": "sweepNum"
            },                    {
                "type": "input",
                "label": "车皮号",
                "prop": "trainCod"
            },                    {
                "type": "input",
                "label": "车次号",
                "prop": "trainNo"
            },                    {
                "type": "input",
                "label": "单位代码",
                "prop": "unitCod"
            },                    {
                "type": "input",
                "label": "修改人",
                "prop": "updateNam"
            },                    {
                "type": "input",
                "label": "修改时间",
                "prop": "updateTim"
            },                    {
                "type": "input",
                "label": "吨数",
                "prop": "weightWgt"
            },                    {
                "type": "input",
                "label": "库场名",
                "prop": "yardNam"
            },                    {
                "type": "input",
                "label": "库场",
                "prop": "yardNo"
            }            ]
}
