export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "shipNo",
      "prop": "shipNo",
      "span": 12
    },	  {
      "type": "input",
      "label": "shipNam",
      "prop": "shipNam",
      "span": 12
    },	  {
      "type": "input",
      "label": "eShipNam",
      "prop": "eShipNam",
      "span": 12
    },	  {
      "type": "input",
      "label": "callNo",
      "prop": "callNo",
      "span": 12
    },	  {
      "type": "input",
      "label": "imoNo",
      "prop": "imoNo",
      "span": 12
    },	  {
      "type": "input",
      "label": "berthCod",
      "prop": "berthCod",
      "span": 12
    },	  {
      "type": "input",
      "label": "tradeId",
      "prop": "tradeId",
      "span": 12
    },	  {
      "type": "input",
      "label": "inCargoCod",
      "prop": "inCargoCod",
      "span": 12
    },	  {
      "type": "input",
      "label": "inCargoNam",
      "prop": "inCargoNam",
      "span": 12
    },	  {
      "type": "input",
      "label": "outCargoCod",
      "prop": "outCargoCod",
      "span": 12
    },	  {
      "type": "input",
      "label": "outCargoNam",
      "prop": "outCargoNam",
      "span": 12
    },	  {
      "type": "input",
      "label": "inShipCap",
      "prop": "inShipCap",
      "span": 12
    },	  {
      "type": "input",
      "label": "outShipCap",
      "prop": "outShipCap",
      "span": 12
    },	  {
      "type": "input",
      "label": "agentCod",
      "prop": "agentCod",
      "span": 12
    },	  {
      "type": "input",
      "label": "agentNam",
      "prop": "agentNam",
      "span": 12
    },	  {
      "type": "input",
      "label": "toPortTim",
      "prop": "toPortTim",
      "span": 12
    },	  {
      "type": "input",
      "label": "levPortTim",
      "prop": "levPortTim",
      "span": 12
    },	  {
      "type": "input",
      "label": "tallyCod",
      "prop": "tallyCod",
      "span": 12
    },	  {
      "type": "input",
      "label": "tallyNam",
      "prop": "tallyNam",
      "span": 12
    },	  {
      "type": "input",
      "label": "entrustCod",
      "prop": "entrustCod",
      "span": 12
    },	  {
      "type": "input",
      "label": "entrustNam",
      "prop": "entrustNam",
      "span": 12
    }  ]
}
