export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "备注",
      "prop": "markTxt"
    },	  {
      "type": "input",
      "label": "操作员",
      "prop": "operNam"
    },	  {
      "type": "input",
      "label": "计划日期",
      "prop": "planDte"
    },	  {
      "type": "input",
      "label": "计划号",
      "prop": "planNo"
    },	  {
      "type": "input",
      "label": "记录时间",
      "prop": "recordTim"
    },	  {
      "type": "input",
      "label": "序号",
      "prop": "seqNo"
    },	  {
      "type": "input",
      "label": "管货库区代码",
      "prop": "subunitCod"
    },	  {
      "type": "input",
      "label": "管货库区",
      "prop": "subunitNam"
    },	  {
      "type": "input",
      "label": "股位代码",
      "prop": "trackCod"
    },	  {
      "type": "input",
      "label": "股位",
      "prop": "trackNam"
    },	  {
      "type": "input",
      "label": "车数",
      "prop": "trainNum"
    },	  {
      "type": "input",
      "label": "作业公司代码",
      "prop": "unitCod"
    },	  {
      "type": "input",
      "label": "作业公司",
      "prop": "unitNam"
    },	  {
      "type": "input",
      "label": "集疏港别",
      "prop": "unloadId"
    },	  {
      "type": "input",
      "label": "修改人",
      "prop": "updateNam"
    },	  {
      "type": "input",
      "label": "修改时间",
      "prop": "updateTim"
    },	  {
      "type": "input",
      "label": "重量",
      "prop": "weightWgt"
    },	  {
      "type": "input",
      "label": "库场名称",
      "prop": "yardNam"
    },	  {
      "type": "input",
      "label": "库场代码",
      "prop": "yardNo"
    }  ]
}
