export const tableOption = {
    "border": true,
    "filterBtn": false,
     refreshBtn:false,
    "index": true,
    addBtn:false,
    columnBtn:false,
    "indexLabel": "序号",
    "stripe": true,
    "menuAlign": "center",
    "align": "center",
    "size": "mini",
    "selection": false,
    "searchMenuSpan": 6,
    "selectionWidth": 40,
    "menuWidth": 160,
    "menuPosition": "center",
    delBtn:false,
    editBtn:false,
    "height": 650,
    "column": [
        {
            "type": "input",
            "label": "客户代码",
            "prop": "agentCod",
            "hide": false,
            width: 150,
            "fixed": true,
        },{
            "type": "input",
            "label": "客户名称",
            "prop": "agentNam",
            "hide": false,
            width: 250,
            "fixed": true,
        },
        {
            "type": "input",
            "label": "状态",
            "prop": "useId",
            "hide": false,
            "slot": true,
            width: 100,
            "fixed": true,
        },
        {
            "type": "input",
            "label": "客户地址",
            "prop": "agentAddr",
            "hide": false,
            width: 250,
        }, {
            "type": "input",
            "label": "开户行",
            "prop": "agentBank",
            "hide": false,
            width: 250,
        },  {
            "type": "input",
            "label": "客户传真",
            "prop": "agentFax",
            "hide": false,
            width: 250,
        }, {
            "type": "input",
            "label": "客户类型",
            "prop": "agentKind",
            "hide": false,
            width: 100,
        }, {
            "type": "input",
            "label": "客户电话",
            "prop": "agentPhoen",
            "hide": false,
            width: 150,
        }, {
            "type": "input",
            "label": "邮编",
            "prop": "agentPostcode",
            "hide": false,
            width: 150,
        }, {
            "type": "input",
            "label": "账号",
            "prop": "agnetAccount",
            "hide": false,
            width: 250,
        },
       
        {
            "type": "input",
            "label": "封存",
            "prop": "fcId",
            "hide": true,
            
        },{
            "type": "input",
            "label": "$column.comments",
            "prop": "belongPartyName",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "date01",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "date02",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "date03",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "fapiaoLei",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "flag01",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "flag02",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "flag03",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "linkMan",
            "hide": true,
        }, {
            "type": "input",
            "label": "港融绑定外围用户代码",
            "prop": "outUserId",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "pkid",
            "hide": true,
        }, {
            "type": "input",
            "label": "是否是港容平台",
            "prop": "ptId",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "ref01",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "ref02",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "ref03",
            "hide": true,
        }, {
            "type": "input",
            "label": "备注",
            "prop": "remark",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperIrdNo",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "userCode",
            "hide": true,
        }]
}
