export const tableOption = {
    "border": true,
    "filterBtn": false,
     refreshBtn:false,
     addBtn:false,
     delBtn:false,
     editBtn:false,
     columnBtn:false,
    "index": true,
    "indexLabel": "序号",
    "stripe": true,
    "menuAlign": "center",
    "align": "center",
    "size": "mini",
    "selection": false,
    "searchMenuSpan": 6,
    "selectionWidth": 40,
    "menuWidth": 160,
    "menuPosition": "center",
    "height": 530,
    "column": [
        //-----------------页面显示区域------------------------
        {
            "type": "input",
            "label": "船号(船代)",
            "prop": "shipNoS",
            "hide": false,
            "fixed": true
        },
        {
            "type": "input",
            "label": "船号(集团)",
            "prop": "shipNo",
            "hide": false,
            "fixed": true
        },
        {
            "type": "input",
            "label": "船名",
            "prop": "shipNam",
            "hide": false,
            "fixed": true
        },
        {
            "type": "input",
            "label": "状态",
            "prop": "zt",
            "hide": false,
            "fixed": true,
            "slot": true,
            width: 120,
        },

        {
            "type": "input",
            "label": "支付状态",
            "prop": "zfzt",
            "hide": false,
            "slot": true,
            width: 120,
        },
        {
            "type": "input",
            "label": "结算审核",
            "prop": "dsjBegin",
            "hide": false,
            "slot": true,
            width: 100,
        },
        {
            "type": "input",
            "label": "呼号",
            "prop": "callNo",
            "hide": false,
            width: 100,
        },
        {
            "type": "input",
            "label": "进出口",
            "prop": "flag00",
            "hide": false,
            "slot": true,
        },
        {
            "type": "input",
            "label": "备注",
            "prop": "boomStr",
            "hide": false,
            width: 160,
        },
        {
            "type": "input",
            "label": "离港时间",
            "prop": "levPortTim",
            "hide": false,
            width: 160,
        },
        {
            "type": "input",
            "label": "装卸",
            "prop": "unloadId",
            "hide": false,
            "slot": true,
        },
        {
            "type": "input",
            "label": "内外贸",
            "prop": "tradeId",
            "hide": false,
            "slot": true,
        },
        {
            "type": "input",
            "label": "进口货名",
            "prop": "inCargoNam",
            "hide": false,
            "width": "150px",
        }, {
            "type": "input",
            "label": "进口重量",
            "prop": "inShipCap",
            "hide": false,
        }, {
            "type": "input",
            "label": "出口货名",
            "prop": "outCargoNam",
            "hide": false,
            "width": "150px",
        }, {
            "type": "input",
            "label": "出口重量",
            "prop": "outShipCap",
            "hide": false,
        }, {
            "type": "input",
            "label": "净重",
            "prop": "netWgt",
            "hide": false,
        },
        {
            "type": "input",
            "label": "载重吨",
            "prop": "shipCap",
            "hide": false,
        }, {
            "type": "input",
            "label": "总长度",
            "prop": "shipLongNum",
            "hide": false,
        },
        {
            "type": "input",
            "label": "报港单位",
            "prop": "shipperDoc",
            "hide": false,
            "width": "250px",
        },
        {
            "type": "input",
            "label": "来港",
            "prop": "fromPortNam",
            "hide": false,
        }, {
            "type": "input",
            "label": "往港",
            "prop": "toPortNam",
            "hide": false,
        }, {
            "type": "input",
            "label": "报港时间",
            "prop": "recordTim",
            "hide": false,
            "width": "160px",
        },
        {
            "type": "input",
            "label": "预抵时间",
            "prop": "edtArivTim",
            "hide": false,
            "width": "160px",
        }, {
            "type": "input",
            "label": "船类型",
            "prop": "shipTypNam",
            "hide": false,
        }, {
            "type": "input",
            "label": "船舶代理公司",
            "prop": "agentNam",
            "hide": false,
            "width": "250px",
        }, {
            "type": "input",
            "label": "发票类型",
            "prop": "fapiaoLei",
            "hide": false,
            "slot": true,
            "width": "180px",
        }, {
            "type": "input",
            "label": "清污协议",
            "prop": "cleanprot",
            "hide": false,
            "slot": true,
        },
        //-------------------------------------------------
        {
            "type": "input",
            "label": "$column.comments",
            "prop": "agentCheck",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "代理代码",
            "prop": "agentCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "联系单位代码",
            "prop": "agentCod01",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "agentKnd",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "联系单位名称",
            "prop": "agentNam_02",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "联系电话",
            "prop": "agentPhone",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "联系人",
            "prop": "agentXingming",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "amt",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "锚位",
            "prop": "anchorPositioan",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "前缆桩",
            "prop": "anteCable",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "抵港标志 默认为0",
            "prop": "arivportId",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "抵港艏吃水",
            "prop": "arrivHeadWat",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "抵港平均赤水",
            "prop": "arrivMidWat",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "离港艏赤水",
            "prop": "arrivTailWat",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "回退标志 1回退 0不回退",
            "prop": "backId",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "泊位号",
            "prop": "berthCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "停靠方式",
            "prop": "berthWay",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "水路运单类型 【0/null：线上水路运单  1：线下水路运单】",
            "prop": "billwayType",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "备注",
            "prop": "boomStr",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船长证书号",
            "prop": "captainCertificate",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船长姓名中/ 英",
            "prop": "captainName",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船长电话",
            "prop": "captainTel",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "运费",
            "prop": "carriage",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船籍代码",
            "prop": "countryCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "生成PDF状态 1:未生成 2:已生成",
            "prop": "createPdfStatus",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "海关编码",
            "prop": "customNo",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船籍名称",
            "prop": "cCountryNam",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "date00",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "date01",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "date02",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "离港地点代码",
            "prop": "departPortCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "吊杆负荷",
            "prop": "derrickCap",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "卸货开始时间",
            "prop": "discBegTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "卸货结束时间",
            "prop": "discEndTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "djr",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "djrPhone",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "委托人代码",
            "prop": "entrustCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "委托人",
            "prop": "entrustNam",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "etdLeavTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "出口舱口数",
            "prop": "expHatchNum",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "英文船名",
            "prop": "eShipName",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "减免代码",
            "prop": "feeCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "减免审核标志",
            "prop": "feeId",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "减免名称",
            "prop": "feeName",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "flag01",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "flag02",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "预报标志",
            "prop": "forCastId",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "老港代码",
            "prop": "fromPortCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船舶初次登记号",
            "prop": "fShipperNo",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "gangqu",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "gatherId",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "会员代码",
            "prop": "hydm",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "hyname",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "ifBack",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "IMO_NO",
            "prop": "imoNo",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "舱口数",
            "prop": "impHatchNum",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "初次登记号",
            "prop": "initRegisterNumber",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "进口货名代码",
            "prop": "inCargoCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "进口货类",
            "prop": "inCargoKnd",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "实际卸货",
            "prop": "inFactTon",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "进口理货吨数",
            "prop": "inTallyCap",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "进口TEU",
            "prop": "inTeuNum",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "进口航次",
            "prop": "inVoyage",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "上次安检时间",
            "prop": "lastScTime",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "离港平均赤水",
            "prop": "levHeadWat",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "离港艏赤水",
            "prop": "levMidWat",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "离港记录时间",
            "prop": "levRecordTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "levTailWat",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "装货开始时间",
            "prop": "loadBegTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "装货结束时间",
            "prop": "loadEndTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "实际运营方",
            "prop": "mainShipperCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "实际运营方",
            "prop": "mainShipperName",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "建造日期",
            "prop": "makeTime",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "备注",
            "prop": "markTxt",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "集港开始时间",
            "prop": "massBegTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "集港结束时间",
            "prop": "massEndTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船货代代码",
            "prop": "mbdm",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "mbname",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "上油量",
            "prop": "oilTon",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "操作员",
            "prop": "operNam",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "出口货名代码",
            "prop": "outCargoCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "出口货类",
            "prop": "outCargoKnd",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "实际装货",
            "prop": "outFactTon",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "出口理货吨数",
            "prop": "outTallyCap",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "出口TEU",
            "prop": "outTeuNum",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "出口航次",
            "prop": "outVoyage",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "phzt",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "是否引航:0是,1否",
            "prop": "pilotage",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "引航否",
            "prop": "pilotId",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "备车时间",
            "prop": "prepareTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "prePortCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "prePortNam",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "速遣标志",
            "prop": "quickId",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "审核不通过原因",
            "prop": "reason",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "ref00",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "ref01",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "ref02",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "本港是否安检1:是2:否",
            "prop": "securityCheckType",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "sendShipCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "settleType",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperAcn",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperAdd",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperCodPrice",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperDocPrice",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperIrdNo",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船舶种类",
            "prop": "shipKindId",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "航线代码",
            "prop": "shipLineCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "航线名称",
            "prop": "shipLineNam",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船舶性质",
            "prop": "shipNatId",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船主代码",
            "prop": "shipOwnerCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船主名称",
            "prop": "shipOwnerNam",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "单/双壳  1:单壳 2双壳",
            "prop": "shipShell",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船型代码",
            "prop": "shipTypCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "船宽",
            "prop": "shipWideNum",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shr",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "后缆桩",
            "prop": "stepCable",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "是否理货:0是,1否",
            "prop": "tally",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "理货单位代码",
            "prop": "tallyCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "理货单位",
            "prop": "tallyNam",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "总重",
            "prop": "totalWgt",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "靠泊时间",
            "prop": "toBerthTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "往港代码",
            "prop": "toPortCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "抵锚时间",
            "prop": "toPortTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "抵港记录时间",
            "prop": "toRecordTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "是否拖轮:0是,1否",
            "prop": "tug",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "拖轮否",
            "prop": "tugboatId",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "轮机长证书号",
            "prop": "turbineCertificate",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "轮机长姓名",
            "prop": "turbineName",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "型深",
            "prop": "typeDeepNum",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "单位代码",
            "prop": "unitCod",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "单位名称",
            "prop": "unitNam",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "最终修改时间",
            "prop": "updateNam",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "最终修改人",
            "prop": "updateTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "疏港开始时间",
            "prop": "vacatBegTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "疏港结束时间",
            "prop": "vacatEndTim",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "ywyphone",
            "hide": true,
            showColumn:false,
        }, {
            "type": "input",
            "label": "上报",
            "prop": "reportId",
            "hide": true,
            "fixed": true,
            "slot": true,
            showColumn:false,
        },]
}
