export const tableOption = {
    "border": true,
    "filterBtn": true,
    "index": true,
    "indexLabel": "序号",
    "stripe": true,
    "menuAlign": "center",
    "align": "center",
    "size": "mini",
    "selection": true,
    "searchMenuSpan": 6,
    "selectionWidth": 40,
    "menuWidth": 160,
    "menuPosition": "center",
    "height": 550,
    "column": [
        {
            "type": "input",
            "label": "船号",
            "prop": "shipNo",
            "hide": false,
            "fixed": true
        }, {
            "type": "input",
            "label": "船名",
            "prop": "shipNam",
            "hide": false,
            "fixed": true
        }, {
            "type": "input",
            "label": "上报",
            "prop": "reportId",
            "hide": false,
            "slot": true,
        },{
            "type": "input",
            "label": "船舶性质",
            "prop": "shipNatId",
            "hide": true,
            "fixed": true
        },{
            "type": "input",
            "label": "内外贸",
            "prop": "tradeId",
            "hide": false,
            "slot": true
        }, {
            "type": "input",
            "label": "拖轮否",
            "prop": "tugboatId",
            "hide": false,
        }, {
            "type": "input",
            "label": "记录时间",
            "prop": "recordTim",
            "hide": true,
        },{
            "type": "input",
            "label": "预抵时间",
            "prop": "edtArivTim",
            "hide": false,
            "width":"180px"
        }, {
            "type": "input",
            "label": "进口货名代码",
            "prop": "inCargoCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "进口货类",
            "prop": "inCargoKnd",
            "hide": true,
        }, {
            "type": "input",
            "label": "进口货名",
            "prop": "inCargoNam",
            "hide": false,
        }, 
        {
            "type": "input",
            "label": "出口货名",
            "prop": "outCargoNam",
            "hide": false,
        },{
            "type": "input",
            "label": "进口航次",
            "prop": "inVoyage",
            "hide": false,
        }, {
            "type": "input",
            "label": "出口航次",
            "prop": "outVoyage",
            "hide": false,
        },{
            "type": "input",
            "label": "来港代码",
            "prop": "fromPortCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "来港",
            "prop": "fromPortNam",
            "hide": false,
        },  {
            "type": "input",
            "label": "往港代码",
            "prop": "toPortCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "往港",
            "prop": "toPortNam",
            "hide": false,
        },{
            "type": "input",
            "label": "舱口数",
            "prop": "impHatchNum",
            "hide": true,
        }, {
            "type": "input",
            "label": "实际卸货",
            "prop": "inFactTon",
            "hide": true,
        }, {
            "type": "input",
            "label": "进口重量",
            "prop": "inShipCap",
            "hide": false,
        }, {
            "type": "input",
            "label": "进口TEU",
            "prop": "inTeuNum",
            "hide": false,
        },  {
            "type": "input",
            "label": "出口货名代码",
            "prop": "outCargoCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "出口货类",
            "prop": "outCargoKnd",
            "hide": true,
        }, {
            "type": "input",
            "label": "出口重量",
            "prop": "outShipCap",
            "hide": false,
        }, {
            "type": "input",
            "label": "出口TEU",
            "prop": "outTeuNum",
            "hide": false,
        }, {
            "type": "input",
            "label": "引航否",
            "prop": "pilotId",
            "hide": true,
        },{
            "type": "input",
            "label": "$column.comments",
            "prop": "agentCheck",
            "hide": true,
        }, {
            "type": "input",
            "label": "代理代码",
            "prop": "agentCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "agentCod_01",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "agentKnd",
            "hide": true,
        }, {
            "type": "input",
            "label": "船舶代理",
            "prop": "agentNam",
            "hide": false,
            "width":"250px"
        }, {
            "type": "input",
            "label": "船舶代理2",
            "prop": "agentNam_02",
            "hide": false,
            "width":"250px"
        }, {
            "type": "input",
            "label": "代理联系电话",
            "prop": "agentPhone",
            "hide": false,
            "width":"180px"
        }, {
            "type": "input",
            "label": "代理人",
            "prop": "agentXingming",
            "hide": false,
        }, {
            "type": "input",
            "label": "锚位",
            "prop": "anchorPositioan",
            "hide": false,
        }, {
            "type": "input",
            "label": "前缆桩",
            "prop": "anteCable",
            "hide": false,
        }, {
            "type": "input",
            "label": "抵港标志",
            "prop": "arivportId",
            "hide": true,
        }, {
            "type": "input",
            "label": "抵港艏吃水",
            "prop": "arrivHeadWat",
            "hide": true,
        }, {
            "type": "input",
            "label": "抵港平均吃水",
            "prop": "arrivMidWat",
            "hide": true,
        }, {
            "type": "input",
            "label": "抵港艉吃水",
            "prop": "arrivTailWat",
            "hide": true,
        }, {
            "type": "input",
            "label": "回退标志 1回退 0不回退",
            "prop": "backId",
            "hide": true,
        }, {
            "type": "input",
            "label": "泊位号",
            "prop": "berthCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "停靠方式",
            "prop": "berthWay",
            "hide": true,
        }, {
            "type": "input",
            "label": "备注",
            "prop": "boomStr",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "callNo",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "cleanprot",
            "hide": true,
        }, {
            "type": "input",
            "label": "船籍代码",
            "prop": "countryCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "海关编码",
            "prop": "customNo",
            "hide": true,
        }, {
            "type": "input",
            "label": "中文国籍",
            "prop": "cCountryNam",
            "hide": true,
        }, {
            "type": "input",
            "label": "离港地点代码",
            "prop": "departPortCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "吊杆负荷",
            "prop": "derrickCap",
            "hide": true,
        }, {
            "type": "input",
            "label": "卸货开始时间",
            "prop": "discBegTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "卸货结束时间",
            "prop": "discEndTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "委托人代码",
            "prop": "entrustCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "委托人",
            "prop": "entrustNam",
            "hide": true,
        }, {
            "type": "input",
            "label": "预抵时间",
            "prop": "etdLeavTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "出口舱口数",
            "prop": "expHatchNum",
            "hide": true,
        }, {
            "type": "input",
            "label": "发票类型",
            "prop": "fapiaoLei",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "flagId",
            "hide": true,
        }, {
            "type": "input",
            "label": "预报标志",
            "prop": "forCastId",
            "hide": true,
        }, {
            "type": "input",
            "label": "离港艏吃水",
            "prop": "levHeadWat",
            "hide": true,
        }, {
            "type": "input",
            "label": "离港平均吃水",
            "prop": "levMidWat",
            "hide": true,
        }, {
            "type": "input",
            "label": "离港时间",
            "prop": "levPortTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "离港记录时间",
            "prop": "levRecordTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "离港艉吃水",
            "prop": "levTailWat",
            "hide": true,
        }, {
            "type": "input",
            "label": "装货开始时间",
            "prop": "loadBegTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "装货结束时间",
            "prop": "loadEndTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "实际运营方",
            "prop": "mainShipperCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "实际运营方",
            "prop": "mainShipperName",
            "hide": true,
        }, {
            "type": "input",
            "label": "备注",
            "prop": "markTxt",
            "hide": true,
        }, {
            "type": "input",
            "label": "集港开始时间",
            "prop": "massBegTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "集港结束时间",
            "prop": "massEndTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "净吨",
            "prop": "netWgt",
            "hide": true,
        }, {
            "type": "input",
            "label": "上油量",
            "prop": "oilTon",
            "hide": true,
        }, {
            "type": "input",
            "label": "操作员",
            "prop": "operNam",
            "hide": true,
        },  {
            "type": "input",
            "label": "实际装货",
            "prop": "outFactTon",
            "hide": true,
        },
        
        
        
        
        
         {
            "type": "input",
            "label": "备车时间",
            "prop": "prepareTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "prePortCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "prePortNam",
            "hide": true,
        }, {
            "type": "input",
            "label": "速遣标志",
            "prop": "quickId",
            "hide": true,
        }, {
            "type": "input",
            "label": "班轮否(1班轮，0普通)",
            "prop": "regularId",
            "hide": true,
        },  {
            "type": "input",
            "label": "0 对派 1我派",
            "prop": "sendShipCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperAcn",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperAdd",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperDoc",
            "hide": true,
        }, {
            "type": "input",
            "label": "$column.comments",
            "prop": "shipperIrdNo",
            "hide": true,
        }, {
            "type": "input",
            "label": "总载重量",
            "prop": "shipCap",
            "hide": true,
        }, {
            "type": "input",
            "label": "船舶种类",
            "prop": "shipKindId",
            "hide": true,
        }, {
            "type": "input",
            "label": "航线代码",
            "prop": "shipLineCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "航线名称",
            "prop": "shipLineNam",
            "hide": true,
        }, {
            "type": "input",
            "label": "总长度",
            "prop": "shipLongNum",
            "hide": true,
        }, {
            "type": "input",
            "label": "船主代码",
            "prop": "shipOwnerCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "船主",
            "prop": "shipOwnerNam",
            "hide": true,
        }, {
            "type": "input",
            "label": "船型代码",
            "prop": "shipTypCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "船型",
            "prop": "shipTypNam",
            "hide": true,
        }, {
            "type": "input",
            "label": "后缆桩",
            "prop": "stepCable",
            "hide": true,
        }, {
            "type": "input",
            "label": "理货单位代码",
            "prop": "tallyCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "理货单位",
            "prop": "tallyNam",
            "hide": true,
        }, {
            "type": "input",
            "label": "总吨",
            "prop": "totalWgt",
            "hide": true,
        }, {
            "type": "input",
            "label": "靠泊时间",
            "prop": "toBerthTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "抵锚时间",
            "prop": "toPortTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "抵港记录时间",
            "prop": "toRecordTim",
            "hide": true,
        },  {
            "type": "input",
            "label": "单位代码",
            "prop": "unitCod",
            "hide": true,
        }, {
            "type": "input",
            "label": "单位名称",
            "prop": "unitNam",
            "hide": true,
        }, {
            "type": "input",
            "label": "最终修改人",
            "prop": "updateNam",
            "hide": true,
        }, {
            "type": "input",
            "label": "最终修改时间",
            "prop": "updateTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "疏港开始时间",
            "prop": "vacatBegTim",
            "hide": true,
        }, {
            "type": "input",
            "label": "疏港结束时间",
            "prop": "vacatEndTim",
            "hide": true,
        }]
}
