export const tableOption = {
    "border": true,
    "filterBtn":true,
    "index": true,
    "indexLabel": "序号",
    "stripe": true,
    "menuAlign": "center",
    "align": "center",
    "size":"mini",
    "selection":true,
    "searchMenuSpan": 6,
    "selectionWidth":40,
    "menuWidth":160,
    "menuPosition":"center",
    "height":550,
    "column": [
                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "agentAddr"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "agentBank"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "agentCod"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "agentFax"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "agentKind"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "agentNam"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "agentPhoen"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "agentPostcode"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "agnetAccount"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "bussMan"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "cdPrepay"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "cdRemark"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "confirmId"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "confirmMan"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "jsId"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "jsMny"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "oldVoyageBal"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "operNam"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "payDte"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "payMan"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "payNo"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "payWay"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "planMan"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "recordTim"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "remark"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "seqNo"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "shipBillNo"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "shipNam"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "shipNo"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "takeFax"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "takeMan"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "takePhone"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "unitCod"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "unitNam"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "updateNam"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "updateTim"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "verNo"
            },                    {
                "type": "input",
                "label": "$column.comments",
                "prop": "voyageMny"
            }            ]
}
