export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "menuWidth": "140",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	{
      "type": "input",
      "label": "公司代码",
      "prop": "companyCode",
      "search":true,
      "span": 12,
      "sortable": true
    },	  {
      "type": "input",
      "label": "公司名称",
      "prop": "company",
      "search":true,
      "span": 12,
      "width": 160,
      "sortable": true
    },	  {
      "type": "input",
      "label": "联系人",
      "sortable": true,
      "prop": "contactName",
      "span": 12
    },	  {
      "type": "input",
      "label": "联系人电话",
      "sortable": true,
      "width": 120,
      "prop": "contactPhone",
      "span": 12
    },	  {
      "type": "input",
      "label": "营业执照号",
      "prop": "businessLicenseNumber",
      "sortable": true,
      "width": 160,
      "span": 12
    },	  {
      "type": "input",
      "label": "法人",
      "sortable": true,
      "prop": "legalPerson",
      "span": 12,
    },	  {
      "type": "input",
      "label": "法人证件号",
      "sortable": true,
      "prop": "certificateNumber",
      "width": 160,
      "span": 12
    },	  {
      "type": "input",
      "label": "公司地址",
      "sortable": true,
      "prop": "address",
      "width": 160,
      "span": 12
    },	  {
      "type": "input",
      "label": "公司电话",
      "sortable": true,
      "prop": "companyPhone",
      "width": 120,
      "span": 12
    },	  {
      "type": "input",
      "label": "银行账号",
      "sortable": true,
      "prop": "bankAccount",
      "width": 160,
      "span": 12
    },	  {
      "type": "input",
      "label": "开户行名称",
      "sortable": true,
      "prop": "openingBank",
      "width": 160,
      "span": 12
    },	  {
      "type": "input",
      "label": "开户名",
      "sortable": true,
      "prop": "accountName",
      "width": 120,
      "span": 12
    },	  {
      "type": "input",
      "label": "联系人邮箱",
      "sortable": true,
      "prop": "contactMail",
      "width": 120,
      "span": 12
    },	  {
      "type": "input",
      "label": "备注",
      "sortable": true,
      "prop": "remark",
      "span": 12
    }]
}
