export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "agentCod",
      "prop": "agentCod",
      "span": 12
    },	  {
      "type": "input",
      "label": "agentNam",
      "prop": "agentNam",
      "span": 12
    },	  {
      "type": "input",
      "label": "engAgentNam",
      "prop": "engAgentNam",
      "span": 12
    },	  {
      "type": "input",
      "label": "agentNo",
      "prop": "agentNo",
      "span": 12
    },	  {
      "type": "input",
      "label": "agentShort",
      "prop": "agentShort",
      "span": 12
    },	  {
      "type": "input",
      "label": "corporation",
      "prop": "corporation",
      "span": 12
    },	  {
      "type": "input",
      "label": "telephone",
      "prop": "telephone",
      "span": 12
    },	  {
      "type": "input",
      "label": "eMail",
      "prop": "eMail",
      "span": 12
    }  ]
}
